### ISSUE TITLE
Table baru untuk validasi Kelompok LSM

### ISSUE THREAD

**Issue by ziezah** [vynhart/bnsskzzh#11]
1. Import data ke mysql
2. Hapus Field Nama Kelompok dan Tanggal Terdaftar dari Form Pendaftaran Kelompok
3. Lakukan pemanggilan ajax untuk validasi kelompok
4. Syarat untuk kelompok mendaftar minimal sudah berdiri 3 tahun dari tanggal berdirinya kelompok

**Comment by vynhart** [comment]
done

**Comment by ziezah** [comment]
Harus tetap di migrasi kan? Tp g perlu ganti nama database
