### ISSUE TITLE
Rekap hasil akhir

### ISSUE THREAD

**Issue by ziezah** [vynhart/bnsskzzh#24]
jika proses semua sudah selesai dan sudah ada hasil proposal yang diterima. ada halaman khusus untuk data yang diterima di satu halaman, yg mungkin bisa diprint.

**Comment by vynhart** [comment]
ini udah kan?

di print gimana lagi maunya..

**Comment by ziezah** [comment]
Udh dikerjain orng pusat yg ini..

**Comment by vynhart** [comment]
oke.
